  - name: Create CDP Enabled Policy
    aci_interface_policy_leaf_policy_group:
        host: "{{ aci_host }}"
        username: "{{ aci_user_name }}"
        private_key: "{{ aci_certificate_path }}"
        certificate_name: "{{ aci_certiciate_name }}"
        validate_certs: "no"
        aep: "FEDLAB-AEP"
        cdp_policy: "cdp-enable"
        port_channel_policy: "lacp-active"
        policy_group: "Sam-Test-Policy-Group"
        lag_type: "node"

