- name: "Modify Web Timeout on {{ inventory_hostname }} "
  aci_rest:
    hostname: "{{ aci_host }}"
    username: "{{ aci_user_name }}"
    private_key: "{{ aci_certificate_path }}"
    certificate_name: "{{ aci_certificate_name }}"
    validate_certs: no
    path: /api/node/mo/uni/userext/pkiext/webtokendata.json
    method: post
    use_proxy: no
    content: |
      {"pkiWebTokenData": { "attributes": {"dn": "uni/userext/pkiext/webtokendata", "uiIdleTimeoutSeconds": "{{ timeout_value }}" }}}
  delegate_to: localhost