  - name: Create LLDP Enabled Policy
    aci_interface_policy_lldp:
      host: "{{ aci_host }}"
      username: "{{ aci_user_name }}"
      private_key: "{{ aci_certificate_path }}"
      certificate_name: "{{ aci_certiciate_name }}"
      validate_certs: no
      lldp_policy: lldp-enable
      receive_state: yes
      transmit_state: yes
      description: Anisible generated Base policy to Enable LLDP bi-directionally
  - name: Create LLDP Disabled Policy
    aci_interface_policy_lldp:
      host: "{{ aci_host }}"
      username: "{{ aci_user_name }}"
      private_key: "{{ aci_certificate_path }}"
      certificate_name: "{{ aci_certiciate_name }}"
      validate_certs: no
      lldp_policy: lldp-disable
      receive_state: no
      transmit_state: no
      description: Anisible generated Base policy to disable LLDP bi-directionally

