- name: "Add a new {{ vlan_domain_type }} domain {{ vlan_pool_name }}"
  cisco.aci.aci_domain:
    use_proxy: no
    validate_certs: "no"
    hostname: "{{ aci_host }}"
    username: "{{ aci_user_name }}"
    private_key: "{{ aci_certificate_path }}"
    certificate_name: "{{ aci_certificate_name }}"
    domain: "{{ domain_name }}"
    domain_type: "{{ vlan_domain_type }}"
    state: present
  delegate_to: localhost

- name: "Map Domain {{ domain_name }} to Pool {{ vlan_pool_name }}"
  cisco.aci.aci_domain_to_encap_pool:
    use_proxy: no
    validate_certs: "no"
    hostname: "{{ aci_host }}"
    username: "{{ aci_user_name }}"
    private_key: "{{ aci_certificate_path }}"
    certificate_name: "{{ aci_certificate_name }}"
    domain: "{{ domain_name }}"
    domain_type: "{{ vlan_domain_type }}"
    pool: "{{ vlan_pool_name }}"
    pool_type: "{{ vlan_pool_type }}"
    pool_allocation_mode: "{{ pool_allocation_mode }}"
    state: present
  delegate_to: localhost 