  - name: Create LLDP Enabled Policy
    aci_interface_policy_lldp:
      host: "{{ aci_host }}"
      username: "{{ aci_user_name }}"
      private_key: "{{ aci_certificate_path }}"
      certificate_name: "{{ aci_certificate_name }}"
      validate_certs: no
      lldp_policy: lldp-enable
      receive_state: yes
      transmit_state: yes
      description: Ansible generated Base policy to Enable LLDP bi-directionally
      use_proxy: no
    delegate_to: localhost
  - name: Create LLDP Disabled Policy
    aci_interface_policy_lldp:
      host: "{{ aci_host }}"
      username: "{{ aci_user_name }}"
      private_key: "{{ aci_certificate_path }}"
      certificate_name: "{{ aci_certificate_name }}"
      validate_certs: no
      lldp_policy: lldp-disable
      receive_state: no
      transmit_state: no
      description: Ansible generated Base policy to disable LLDP bi-directionally
      use_proxy: no
    delegate_to: localhost
