- name: "Modify COOP Policy Default on {{ inventory_hostname }} "
  aci_rest:
    hostname: "{{ aci_host }}"
    username: "{{ aci_user_name }}"
    private_key: "{{ aci_certificate_path }}"
    certificate_name: "{{ aci_certificate_name }}"
    validate_certs: no
    path: /api/node/mo/uni/userext/user-ansible/userdomain-all.json
    method: post
    content: |
      {
         "coopPol": {
            "attributes":{
               "type":"strict",
               "dn":"uni/fabric/pol-default"
            }
         }
      }
    use_proxy: no
  delegate_to: localhost

      

