---
- name: Check Tenants 
  hosts: localhost
  vars:
    aci_host: 1.1.1.1
    aci_user_name: Ansible
    aci_certificate_name: ansible
    aci_certificate_path: /root/certs/ansible.key
  gather_facts: no
  connection: local
  tasks:
  - name: Ensure tenant ABC exists
    aci_rest:
      use_proxy: false
      host: "{{ aci_host }}"
      username: "{{ aci_user_name }}"
      certificate_name: "{{ aci_certificate_name }}"
      method: get
      path: /api/node/class/fvTenant.json
      validate_certs: no 
      private_key: "{{ aci_certificate_path }}"
    delegate_to: localhost