---
- name: Check Tenants 
  hosts: Example
  gather_facts: no
  connection: local
  tasks:
  - name: Ensure tenant ABC exists
    aci_rest:
      use_proxy: false
      host: "{{ aci_host }}"
      username: "{{ aci_user_name }}"
      certificate_name: "{{ aci_certificate_name }}"
      method: get
      path: /api/node/class/fvTenant.json
      validate_certs: no 
      private_key: "{{ aci_certificate_path }}"
    delegate_to: localhost
    register: query_result