---

  - name: "Configure Default Policies common to most environments"
    gather_facts: no
    connection: local
    hosts: demoExample
    tasks:
    - name: Import CDP Policy Tasks
      import_tasks: tasks/task-cdp-neighbor-policies.yaml

    - name: Import LLDP Policy Tasks
      import_tasks: tasks/task-lldp-neighbor-policies.yaml

    - name: Import LACP Policy Tasks
      import_tasks: tasks/task-port-channel-policies.yaml
    
    - name: Import COOP Default Policy Task
      import_tasks: tasks/task-default-coop-policy.yaml
