  - name: "Pools, Domains and AEP Configuration"
    gather_facts: no
    connection: local
    hosts: fedlabaci
    vars:
     aep_name: "FEDLAB-AEP"
     vlan_pool_name: "Demo"
     vlan_pool_description: "Demo VLAN Pool"
     vlan_pool_allocation_mode: "static"
    tasks:
    - name: "Create VLAN Pool {{ vlan_pool_name }}"
      import_tasks: tasks/task-create-VLAN-Pool.yaml
    - name: "Create AEP {{ aep_name }}"
      import_tasks: tasks/task-create-aep.yaml  