---

  - name: "Configure Default Policies common to most environments"
    gather_facts: no
    connection: local
    hosts: fedlabaci
    tasks:
    - name: Import CDP Policy Tasks
      import_tasks: tasks/task-cdp-neighbor-policies.yaml

    - name: Import LLDP Policy Tasks
      import_tasks: tasks/task-lldp-neighbor-policies.yaml
