  - name: "Tenant EPG Operations"
    gather_facts: no
    connection: local
    hosts: demoExample
    vars:
      TenantName: "Sam-API-Demo"
      VRF_Name: "Sam-API-Demo-VRF"
      BD_Name: "Sam-Demo1-BD"
      BD_Gateway: "192.168.99.1"  # The gateway for the bridge Bridge Domain Domain
      BD_Mask: 24                 # The mask for the gateway on the bridge domain.
      deploymentStatus: "present" # "present" creates these objects, "absent" destroys the demo
      BD_Subnet_Scope: ["shared","public"]   # Advertized outside the fabric and shared between VRFs
      AP_Name: "Sam-Demo-AP"      # Application Profile Name
      EPG_Name: "Sam-Demo-EPG1"   # End Point Group Name
      EPG_Domain_Type: "vmm"      # Specifies Virtual Networking
      EPG_Domain_Provider: "vmware"   # Virtual Networking is VMWare supported
      EPG_Domain_Name: "AJ430_APIC" # Example Domain Name in VMWare VMM integration
    tasks:
    #- name: "Create Elements of the demo"
    - import_tasks: tasks/task-create-tenant.yaml
    - import_tasks: tasks/task-create-vrf.yaml
    - import_tasks: tasks/task-create-BridgeDomain.yaml
    - import_tasks: tasks/task-create-ap.yaml
    - import_tasks: tasks/task-create-epg.yaml